#Requires -Version 7.0
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

<#
.SYNOPSIS
    Convert an IDI IntentGraph into production-ready OpenTofu HCL configuration.

.DESCRIPTION
    ConvertTo-OpenTofuConfig is the bridge between the IDI intent pipeline and
    real OpenTofu infrastructure provisioning. It takes an IntentGraph DAG
    (from ConvertTo-IntentGraph) and generates:

    - Provider blocks with version constraints
    - Resource blocks with full attribute mappings
    - Variable definitions with defaults and validation
    - Output definitions for cross-module references
    - Backend configuration for remote state
    - Module composition (references existing library/infrastructure/modules)
    - Dependency ordering via depends_on and data sources

    Generation strategies:
    - Module: Reference existing AitherZero infra modules (preferred)
    - Inline: Generate standalone resource blocks (for custom resources)
    - Hybrid: Mix modules and inline for resources not covered by modules

    The generated HCL is compatible with:
    - Invoke-AitherInfra (plan/apply against workspace)
    - AitherVeil TerraformGenerator (same variable naming conventions)
    - Genesis /infra/requests (commit → plan → approve → apply)
    - library/infrastructure/modules/* (module sources)

.PARAMETER IntentGraph
    The IntentGraph from ConvertTo-IntentGraph.

.PARAMETER OutputPath
    Directory to write generated .tf files. If omitted, returns HCL as string.

.PARAMETER Strategy
    Generation strategy: Module, Inline, or Hybrid. Default: Module.

.PARAMETER Backend
    State backend: local, s3, azurerm, gcs. Default: local.

.PARAMETER BackendConfig
    Backend-specific config hashtable.

.PARAMETER IncludeVariables
    Generate variables.tf with all extracted variables. Default: true.

.PARAMETER IncludeOutputs
    Generate outputs.tf with resource references. Default: true.

.PARAMETER ModuleSourceBase
    Base path for module sources. Default: ../../modules (relative to env dir).

.PARAMETER Format
    Output format: HCL (native .tf) or JSON (.tf.json). Default: HCL.

.PARAMETER DryRun
    Show what would be generated without writing files.

.PARAMETER PassThru
    Return the generation result object.

.EXAMPLE
    $Graph = ConvertTo-IntentGraph -Intent "Deploy 3 Redis nodes in us-east-1"
    $Graph | ConvertTo-OpenTofuConfig -OutputPath ./environments/dev

.EXAMPLE
    $Graph | ConvertTo-OpenTofuConfig -Strategy Inline -Format JSON -PassThru

.NOTES
    Part of AitherZero Infrastructure pipeline.
    Copyright © 2025-2026 Aitherium Corporation.
#>
function ConvertTo-OpenTofuConfig {
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory, ValueFromPipeline)]
        [PSCustomObject]$IntentGraph,

        [string]$OutputPath,

        [ValidateSet('Module', 'Inline', 'Hybrid')]
        [string]$Strategy = 'Module',

        [ValidateSet('local', 's3', 'azurerm', 'gcs')]
        [string]$Backend = 'local',

        [hashtable]$BackendConfig = @{},

        [bool]$IncludeVariables = $true,

        [bool]$IncludeOutputs = $true,

        [string]$ModuleSourceBase = '../../modules',

        [ValidateSet('HCL', 'JSON')]
        [string]$Format = 'HCL',

        [switch]$DryRun,

        [switch]$PassThru
    )

    process {
        $Provider = $IntentGraph.provider
        $Environment = $IntentGraph.environment
        $Resources = @($IntentGraph.resources)
        $Dependencies = @($IntentGraph.dependencies)

        Write-Host "`n  📝 Generating OpenTofu Configuration" -ForegroundColor Cyan
        Write-Host "  Strategy:    $Strategy" -ForegroundColor Gray
        Write-Host "  Provider:    $Provider" -ForegroundColor Gray
        Write-Host "  Resources:   $($Resources.Count)" -ForegroundColor Gray
        Write-Host "  Environment: $Environment" -ForegroundColor Gray

        # ── Provider → module mapping ─────────────────────────────────────
        $ProviderConfig = _Get-ProviderConfig -Provider $Provider
        $ModuleMap = _Get-ModuleMapping

        # ── Generate HCL blocks ───────────────────────────────────────────
        $MainBlocks = [System.Collections.Generic.List[string]]::new()
        $VariableBlocks = [System.Collections.Generic.List[string]]::new()
        $OutputBlocks = [System.Collections.Generic.List[string]]::new()
        $ModulesUsed = @{}
        $VariablesDefined = @{}

        # Header comment
        $MainBlocks.Add(@"
# =============================================================================
# AitherOS Infrastructure — $($Environment.ToUpper())
# =============================================================================
# Auto-generated by ConvertTo-OpenTofuConfig from IDI IntentGraph
# Intent: $($IntentGraph.intent)
# Hash:   $($IntentGraph.intent_hash)
# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')
# Strategy: $Strategy
# =============================================================================
"@)

        # Terraform block with backend
        $BackendHCL = _Generate-BackendBlock -Backend $Backend -BackendConfig $BackendConfig -Environment $Environment
        $MainBlocks.Add(@"

terraform {
  required_version = ">= 1.6"

  required_providers {
$($ProviderConfig.required_providers)
  }

$BackendHCL
}
"@)

        # Provider block
        $MainBlocks.Add(@"

$($ProviderConfig.provider_block)
"@)

        # ── Process each resource ─────────────────────────────────────────
        foreach ($res in $Resources) {
            $ResType = $res.type         # e.g. 'ec2:instance', 'rds:instance'
            $ResName = $res.name
            $Action = $res.action

            # Skip destroy-only resources in config generation
            if ($Action -eq 'destroy') {
                $MainBlocks.Add("`n# DESTROY target: $ResName ($ResType) — handled by tofu destroy -target")
                continue
            }

            # Find matching module
            $ModuleRef = $ModuleMap[$ResType]

            if ($Strategy -eq 'Module' -and $ModuleRef) {
                # ── Module-based generation ───────────────────────────────
                $ModuleName = $ModuleRef.module
                $ModuleKey = "mod_$($ResName -replace '[^a-z0-9_]', '_')"

                if (-not $ModulesUsed.ContainsKey($ModuleName)) {
                    $ModulesUsed[$ModuleName] = @()
                }
                $ModulesUsed[$ModuleName] += $res

                $ModuleVars = _Map-ResourceToModuleVars -Resource $res -ModuleRef $ModuleRef -Environment $Environment
                $VarLines = ($ModuleVars.GetEnumerator() | ForEach-Object {
                    $val = _Format-HCLValue $_.Value
                    "  $($_.Key) = $val"
                }) -join "`n"

                $MainBlocks.Add(@"

module "$ModuleKey" {
  source      = "$ModuleSourceBase/$ModuleName"
  environment = "$Environment"
$VarLines
}
"@)

                if ($IncludeOutputs) {
                    $OutputBlocks.Add(@"

output "$($ModuleKey)_result" {
  description = "Output from $ModuleKey ($ResType)"
  value       = module.$ModuleKey
}
"@)
                }
            } elseif ($Strategy -eq 'Inline' -or ($Strategy -eq 'Hybrid' -and -not $ModuleRef)) {
                # ── Inline resource generation ────────────────────────────
                $InlineHCL = _Generate-InlineResource -Resource $res -Provider $Provider `
                    -Environment $Environment -Dependencies $Dependencies
                $MainBlocks.Add($InlineHCL.main)

                if ($IncludeOutputs -and $InlineHCL.output) {
                    $OutputBlocks.Add($InlineHCL.output)
                }

                foreach ($varDef in $InlineHCL.variables) {
                    if (-not $VariablesDefined.ContainsKey($varDef.name)) {
                        $VariableBlocks.Add($varDef.hcl)
                        $VariablesDefined[$varDef.name] = $true
                    }
                }
            } else {
                # Hybrid with module available → use module path
                $ModuleName = $ModuleRef.module
                $ModuleKey = "mod_$($ResName -replace '[^a-z0-9_]', '_')"

                $ModuleVars = _Map-ResourceToModuleVars -Resource $res -ModuleRef $ModuleRef -Environment $Environment
                $VarLines = ($ModuleVars.GetEnumerator() | ForEach-Object {
                    $val = _Format-HCLValue $_.Value
                    "  $($_.Key) = $val"
                }) -join "`n"

                $MainBlocks.Add(@"

module "$ModuleKey" {
  source      = "$ModuleSourceBase/$ModuleName"
  environment = "$Environment"
$VarLines
}
"@)
            }
        }

        # ── Standard variables ────────────────────────────────────────────
        if ($IncludeVariables) {
            $StandardVars = @"
# =============================================================================
# Variables — Auto-generated from IDI IntentGraph
# =============================================================================

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "$Environment"
  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be dev, staging, or prod."
  }
}

variable "project" {
  description = "Project name for resource tagging"
  type        = string
  default     = "aitheros"
}

variable "managed_by" {
  description = "Tool managing these resources"
  type        = string
  default     = "opentofu-idi"
}
"@

            $AllVariables = @($StandardVars) + $VariableBlocks
        }

        # ── Assemble final HCL ────────────────────────────────────────────
        $MainHCL = $MainBlocks -join "`n"
        $VariablesHCL = if ($IncludeVariables) { $AllVariables -join "`n" } else { '' }
        $OutputsHCL = if ($IncludeOutputs -and $OutputBlocks.Count -gt 0) {
            @"
# =============================================================================
# Outputs — Auto-generated from IDI IntentGraph
# =============================================================================
$($OutputBlocks -join "`n")
"@
        } else { '' }

        # ── Write or return ───────────────────────────────────────────────
        $Result = [PSCustomObject]@{
            intent_hash    = $IntentGraph.intent_hash
            provider       = $Provider
            environment    = $Environment
            strategy       = $Strategy
            backend        = $Backend
            resources      = $Resources.Count
            modules_used   = @($ModulesUsed.Keys)
            files          = @{}
            generated_at   = [DateTime]::UtcNow.ToString('o')
        }

        if ($Format -eq 'JSON') {
            $Result.files = @{
                'main.tf.json'      = _Convert-HCLToJSON $MainHCL
                'variables.tf.json' = _Convert-HCLToJSON $VariablesHCL
                'outputs.tf.json'   = _Convert-HCLToJSON $OutputsHCL
            }
        } else {
            $Result.files = @{
                'main.tf'      = $MainHCL
                'variables.tf' = $VariablesHCL
                'outputs.tf'   = $OutputsHCL
            }
        }

        if ($OutputPath -and -not $DryRun) {
            if (-not (Test-Path $OutputPath)) {
                New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
            }

            foreach ($file in $Result.files.GetEnumerator()) {
                if ($file.Value) {
                    $FilePath = Join-Path $OutputPath $file.Key
                    if ($PSCmdlet.ShouldProcess($FilePath, "Write HCL file")) {
                        Set-Content -Path $FilePath -Value $file.Value -Encoding UTF8
                        Write-Host "  📄 $($file.Key)" -ForegroundColor Green
                    }
                }
            }

            # Write generation metadata
            $MetaPath = Join-Path $OutputPath '.idi-generation.json'
            @{
                intent_hash  = $IntentGraph.intent_hash
                intent       = $IntentGraph.intent
                provider     = $Provider
                environment  = $Environment
                strategy     = $Strategy
                generated_at = $Result.generated_at
                resources    = $Resources.Count
                modules_used = @($ModulesUsed.Keys)
            } | ConvertTo-Json -Depth 5 | Set-Content -Path $MetaPath -Encoding UTF8
        } elseif ($DryRun) {
            Write-Host "`n  📋 DRY RUN — Would generate:" -ForegroundColor Yellow
            foreach ($file in $Result.files.GetEnumerator()) {
                if ($file.Value) {
                    $LineCount = ($file.Value -split "`n").Count
                    Write-Host "    $($file.Key): $LineCount lines" -ForegroundColor Gray
                }
            }
        }

        Write-Host "`n  ✅ Generated $($Result.files.Count) files for $Provider/$Environment ($Strategy strategy)" -ForegroundColor Green

        if ($PassThru) { return $Result }
    }
}


# ══════════════════════════════════════════════════════════════════════════════
# Internal: Provider configuration
# ══════════════════════════════════════════════════════════════════════════════

function _Get-ProviderConfig {
    param([string]$Provider)

    switch ($Provider) {
        'aws' {
            @{
                required_providers = @'
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
'@
                provider_block = @'
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      environment = var.environment
      project     = var.project
      managed_by  = var.managed_by
    }
  }
}
'@
            }
        }
        'azure' {
            @{
                required_providers = @'
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
'@
                provider_block = @'
provider "azurerm" {
  features {}
  subscription_id = var.azure_subscription_id
}
'@
            }
        }
        'gcp' {
            @{
                required_providers = @'
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
'@
                provider_block = @'
provider "google" {
  project = var.gcp_project_id
  region  = var.gcp_region
}
'@
            }
        }
        'docker' {
            @{
                required_providers = @'
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
'@
                provider_block = @'
provider "docker" {
  host = var.docker_host
}
'@
            }
        }
        'kubernetes' {
            @{
                required_providers = @'
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
'@
                provider_block = @'
provider "kubernetes" {
  config_path    = var.kubeconfig_path
  config_context = var.kube_context
}
'@
            }
        }
        'multi' {
            @{
                required_providers = @'
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
'@
                provider_block = @'
provider "aws" {
  region = var.aws_region
  default_tags { tags = { environment = var.environment; project = var.project; managed_by = var.managed_by } }
}
provider "azurerm" { features {} }
provider "google" { project = var.gcp_project_id; region = var.gcp_region }
'@
            }
        }
    }
}


# ══════════════════════════════════════════════════════════════════════════════
# Internal: IntentGraph resource type → module mapping
# ══════════════════════════════════════════════════════════════════════════════

function _Get-ModuleMapping {
    @{
        # AWS resources → library modules
        'ec2:instance'        = @{ module = 'compute';    var_map = @{ services = 'map'; vpc_id = 'ref'; subnet_ids = 'ref' } }
        'ecs:service'         = @{ module = 'compute';    var_map = @{ services = 'map'; vpc_id = 'ref'; subnet_ids = 'ref' } }
        'eks:cluster'         = @{ module = 'compute';    var_map = @{ services = 'map'; vpc_id = 'ref'; subnet_ids = 'ref' } }
        'vpc:vpc'             = @{ module = 'networking'; var_map = @{ vpc_cidr = 'string'; azs = 'list'; enable_nat = 'bool' } }
        'vpc:subnet'          = @{ module = 'networking'; var_map = @{ vpc_cidr = 'string'; azs = 'list' } }
        'elb:load-balancer'   = @{ module = 'networking'; var_map = @{ vpc_id = 'ref'; subnet_ids = 'ref' } }
        's3:bucket'           = @{ module = 'storage';    var_map = @{ buckets = 'map' } }
        'ebs:volume'          = @{ module = 'storage';    var_map = @{ } }
        'efs:filesystem'      = @{ module = 'storage';    var_map = @{ } }
        'rds:instance'        = @{ module = 'database';   var_map = @{ engine = 'string'; instance_class = 'string'; allocated_storage = 'number' } }
        'rds:aurora'          = @{ module = 'database';   var_map = @{ engine = 'string'; instance_class = 'string' } }
        'elasticache:cluster' = @{ module = 'database';   var_map = @{ engine = 'string' } }
        'dynamodb:table'      = @{ module = 'database';   var_map = @{ } }
        # Docker resources
        'docker:container'    = @{ module = 'containers'; var_map = @{ containers = 'map'; docker_host = 'string' } }
        'docker:compose'      = @{ module = 'containers'; var_map = @{ containers = 'map' } }
        # Kubernetes resources
        'k8s:deployment'      = @{ module = 'deployments'; var_map = @{ namespace = 'string'; deployments = 'map' } }
        'k8s:statefulset'     = @{ module = 'deployments'; var_map = @{ namespace = 'string'; deployments = 'map' } }
        'k8s:service'         = @{ module = 'services';    var_map = @{ namespace = 'string'; services = 'map' } }
    }
}


function _Map-ResourceToModuleVars {
    param($Resource, $ModuleRef, $Environment)

    $Vars = @{}
    $Config = $Resource.config

    switch ($ModuleRef.module) {
        'compute' {
            $ServiceEntry = @{
                image    = $Config.image ?? "ghcr.io/aitherium/$($Resource.name):latest"
                ports    = @($Config.ports ?? @(8080))
                replicas = $Resource.quantity ?? 1
                cpu      = $Config.cpu ?? 256
                memory   = ($Config.memory_gb ?? 1) * 1024
                env      = @{ AITHER_DOCKER_MODE = 'true'; LOG_LEVEL = 'INFO' }
            }
            $Vars['services'] = @{ ($Resource.name) = $ServiceEntry }
        }
        'networking' {
            $Vars['vpc_cidr']    = $Config.cidr ?? '10.0.0.0/16'
            $Vars['enable_nat']  = $Environment -ne 'dev'
        }
        'storage' {
            $BucketEntry = @{
                versioning = $Environment -ne 'dev'
            }
            $Vars['buckets'] = @{ ($Resource.name) = $BucketEntry }
        }
        'database' {
            $Vars['engine']            = $Config.engine ?? 'postgres'
            $Vars['instance_class']    = $Config.instance_type ?? 'db.t3.medium'
            $Vars['allocated_storage'] = $Config.storage_gb ?? 20
        }
        'containers' {
            $ContainerEntry = @{
                image   = $Config.image ?? "ghcr.io/aitherium/$($Resource.name):latest"
                ports   = @(@{ internal = ($Config.port ?? 8080); external = ($Config.port ?? 8080) })
                restart = 'unless-stopped'
                env     = @{ AITHER_DOCKER_MODE = 'true' }
            }
            $Vars['containers'] = @{ ($Resource.name) = $ContainerEntry }
        }
        'deployments' {
            $DeployEntry = @{
                image    = $Config.image ?? "ghcr.io/aitherium/$($Resource.name):latest"
                replicas = $Resource.quantity ?? 1
                ports    = @($Config.port ?? 8080)
                env      = @{ AITHER_DOCKER_MODE = 'true' }
            }
            $Vars['deployments'] = @{ ($Resource.name) = $DeployEntry }
            $Vars['namespace']   = 'aitheros'
        }
        'services' {
            $ServiceDef = @{
                type  = 'ClusterIP'
                ports = @(@{ port = ($Config.port ?? 80); target_port = ($Config.port ?? 8080) })
            }
            $Vars['services']  = @{ ($Resource.name) = $ServiceDef }
            $Vars['namespace'] = 'aitheros'
        }
    }

    return $Vars
}


# ══════════════════════════════════════════════════════════════════════════════
# Internal: Inline HCL generation (when no module exists)
# ══════════════════════════════════════════════════════════════════════════════

function _Generate-InlineResource {
    param($Resource, $Provider, $Environment, $Dependencies)

    $ResType = $Resource.type
    $ResName = $Resource.name -replace '[^a-z0-9_]', '_'
    $Config = $Resource.config
    $Tags = $Resource.tags ?? @{}
    $Quantity = $Resource.quantity ?? 1

    $Main = ''
    $Output = ''
    $Variables = @()

    $TagBlock = ($Tags.GetEnumerator() | ForEach-Object { "    $($_.Key) = `"$($_.Value)`"" }) -join "`n"

    switch -Wildcard ($ResType) {
        'ec2:instance' {
            $Main = @"

resource "aws_instance" "$ResName" {
  count         = $Quantity
  ami           = data.aws_ami.amazon_linux.id
  instance_type = "$($Config.instance_type ?? 't3.medium')"

  tags = {
$TagBlock
    Name = "$ResName-`${count.index}"
  }
}

data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}
"@
            $Output = @"

output "${ResName}_ids" {
  value = aws_instance.${ResName}[*].id
}
"@
        }
        's3:bucket' {
            $Main = @"

resource "aws_s3_bucket" "$ResName" {
  bucket = "$($Resource.name)"
  tags = {
$TagBlock
  }
}

resource "aws_s3_bucket_versioning" "$ResName" {
  bucket = aws_s3_bucket.${ResName}.id
  versioning_configuration {
    status = "$(if ($Environment -eq 'dev') { 'Suspended' } else { 'Enabled' })"
  }
}
"@
            $Output = @"

output "${ResName}_arn" {
  value = aws_s3_bucket.${ResName}.arn
}
"@
        }
        'rds:instance' {
            $Main = @"

resource "aws_db_instance" "$ResName" {
  identifier           = "$($Resource.name)"
  engine               = "$($Config.engine ?? 'postgres')"
  instance_class       = "$($Config.instance_type ?? 'db.t3.medium')"
  allocated_storage    = $($Config.storage_gb ?? 20)
  db_name              = "aitheros"
  username             = "aither_admin"
  manage_master_user_password = true
  skip_final_snapshot  = $(if ($Environment -eq 'dev') { 'true' } else { 'false' })
  tags = {
$TagBlock
  }
}
"@
            $Output = @"

output "${ResName}_endpoint" {
  value     = aws_db_instance.${ResName}.endpoint
  sensitive = false
}
"@
        }
        'elasticache:cluster' {
            $Main = @"

resource "aws_elasticache_cluster" "$ResName" {
  cluster_id           = "$($Resource.name)"
  engine               = "$($Config.engine ?? 'redis')"
  node_type            = "$($Config.instance_type ?? 'cache.t3.medium')"
  num_cache_nodes      = $Quantity
  port                 = 6379
  tags = {
$TagBlock
  }
}
"@
        }
        'vpc:vpc' {
            $Main = @"

resource "aws_vpc" "$ResName" {
  cidr_block           = "$($Config.cidr ?? '10.0.0.0/16')"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = {
$TagBlock
    Name = "$ResName"
  }
}
"@
            $Output = @"

output "${ResName}_id" {
  value = aws_vpc.${ResName}.id
}
"@
        }
        'docker:container' {
            $PortMappings = if ($Config.ports) {
                ($Config.ports | ForEach-Object {
                    "  ports { internal = $_; external = $_ }"
                }) -join "`n"
            } else {
                '  ports { internal = 8080; external = 8080 }'
            }
            $Main = @"

resource "docker_image" "$ResName" {
  name         = "$($Config.image ?? "ghcr.io/aitherium/$($Resource.name):latest")"
  keep_locally = true
}

resource "docker_container" "$ResName" {
  name  = "$($Resource.name)"
  image = docker_image.${ResName}.image_id
  restart = "unless-stopped"
$PortMappings
  labels {
    label = "managed_by"; value = "opentofu"
  }
  labels {
    label = "aither.project"; value = "aitheros"
  }
}
"@
        }
        'k8s:deployment' {
            $Main = @"

resource "kubernetes_deployment" "$ResName" {
  metadata {
    name      = "$($Resource.name)"
    namespace = "aitheros"
    labels    = { app = "$($Resource.name)"; managed_by = "opentofu" }
  }
  spec {
    replicas = $Quantity
    selector { match_labels = { app = "$($Resource.name)" } }
    template {
      metadata { labels = { app = "$($Resource.name)" } }
      spec {
        container {
          name  = "$($Resource.name)"
          image = "$($Config.image ?? "ghcr.io/aitherium/$($Resource.name):latest")"
          port  { container_port = $($Config.port ?? 8080) }
          resources {
            requests = { cpu = "100m"; memory = "128Mi" }
            limits   = { cpu = "500m"; memory = "$($Config.memory_gb ?? 1)Gi" }
          }
        }
      }
    }
  }
}
"@
        }
        default {
            $Main = @"

# Resource: $ResType ($($Resource.name))
# No inline template available — use Module strategy or extend _Generate-InlineResource
# Config: $($Config | ConvertTo-Json -Compress -Depth 3)
"@
        }
    }

    # Check for depends_on from IntentGraph dependencies
    $DependsOn = @($Dependencies | Where-Object { $_.to -eq $Resource.id } | ForEach-Object { $_.from })
    if ($DependsOn.Count -gt 0 -and $Main -match 'resource ') {
        # Insert depends_on before closing brace
        $DependsOnRefs = ($DependsOn | ForEach-Object { "    # dependency: $_" }) -join "`n"
        $Main = $Main -replace '(}\s*$)', "$DependsOnRefs`n`$1"
    }

    return @{
        main      = $Main
        output    = $Output
        variables = $Variables
    }
}


# ══════════════════════════════════════════════════════════════════════════════
# Internal: Backend block generation
# ══════════════════════════════════════════════════════════════════════════════

function _Generate-BackendBlock {
    param($Backend, $BackendConfig, $Environment)

    switch ($Backend) {
        'local' {
            @"
  backend "local" {
    path = ".state/$Environment/terraform.tfstate"
  }
"@
        }
        's3' {
            $Bucket = $BackendConfig.bucket ?? 'aither-tf-state'
            $Region = $BackendConfig.region ?? 'us-east-1'
            @"
  backend "s3" {
    bucket         = "$Bucket"
    key            = "$Environment/terraform.tfstate"
    region         = "$Region"
    encrypt        = true
    dynamodb_table = "aither-tf-locks"
  }
"@
        }
        'azurerm' {
            @"
  backend "azurerm" {
    resource_group_name  = "$($BackendConfig.resource_group ?? 'aitheros-tfstate')"
    storage_account_name = "$($BackendConfig.storage_account ?? 'aitherstate')"
    container_name       = "$($BackendConfig.container ?? 'tfstate')"
    key                  = "$Environment/terraform.tfstate"
  }
"@
        }
        'gcs' {
            @"
  backend "gcs" {
    bucket = "$($BackendConfig.bucket ?? 'aither-tf-state')"
    prefix = "$Environment"
  }
"@
        }
    }
}


# ══════════════════════════════════════════════════════════════════════════════
# Internal: HCL value formatting
# ══════════════════════════════════════════════════════════════════════════════

function _Format-HCLValue {
    param($Value)

    if ($Value -is [bool]) {
        return if ($Value) { 'true' } else { 'false' }
    }
    if ($Value -is [int] -or $Value -is [long] -or $Value -is [double]) {
        return "$Value"
    }
    if ($Value -is [string]) {
        return "`"$Value`""
    }
    if ($Value -is [array]) {
        $Items = $Value | ForEach-Object { _Format-HCLValue $_ }
        return "[$($Items -join ', ')]"
    }
    if ($Value -is [hashtable] -or $Value -is [System.Collections.Specialized.OrderedDictionary]) {
        $Entries = $Value.GetEnumerator() | ForEach-Object {
            "    $($_.Key) = $(_Format-HCLValue $_.Value)"
        }
        return "{`n$($Entries -join "`n")`n  }"
    }

    # PSCustomObject
    if ($Value -is [PSCustomObject]) {
        $Hash = @{}
        $Value.PSObject.Properties | ForEach-Object { $Hash[$_.Name] = $_.Value }
        return _Format-HCLValue $Hash
    }

    return "`"$Value`""
}


function _Convert-HCLToJSON {
    param([string]$HCL)
    # Simple HCL-to-JSON wrapper — for full fidelity use hcl2json
    # This returns the raw HCL wrapped in a JSON structure for tools that prefer JSON
    return @{
        _comment = 'HCL content — use hcl2json for full conversion'
        raw_hcl  = $HCL
    } | ConvertTo-Json -Depth 5
}

Export-ModuleMember -Function ConvertTo-OpenTofuConfig
