<#
.SYNOPSIS
    Deploy AitherClient or AitherNode to a bare metal machine.

.DESCRIPTION
    This script provisions a new machine to join the AitherMesh by:
    1. Connecting via SSH/WinRM to the target machine
    2. Installing prerequisites (Docker/Podman, NVIDIA drivers if GPU)
    3. Deploying AitherClient or AitherNode
    4. Configuring mesh.conf with PSK and controller URL
    5. Starting the mesh agent to auto-join

    Supports both Windows and Linux targets.

.PARAMETER Target
    Target machine hostname or IP address

.PARAMETER Mode
    Deployment mode: "Client" (lightweight) or "Node" (full)

.PARAMETER MeshPSK
    Pre-shared key for mesh authentication

.PARAMETER Controller
    Controller URL or "auto" for discovery

.PARAMETER Services
    List of services to enable (for Node mode)

.PARAMETER GPUEnabled
    Enable GPU support (installs NVIDIA drivers)

.PARAMETER Credential
    PSCredential for SSH/WinRM authentication

.PARAMETER SSHKeyPath
    Path to SSH private key for Linux targets

.PARAMETER Role
    Node role: client, worker, edge

.EXAMPLE
    # Deploy lightweight client
    ./0058_Provision-Aither.ps1 -Target "192.168.1.100" -Mode Client -MeshPSK $env:AITHER_MESH_PSK

.EXAMPLE
    # Deploy full node with specific services
    ./0058_Provision-Aither.ps1 -Target "gpu-server.local" -Mode Node `
        -Services @("AitherParallel", "Ollama") -GPUEnabled -MeshPSK $env:AITHER_MESH_PSK

.EXAMPLE
    # Deploy with SSH key
    ./0058_Provision-Aither.ps1 -Target "ubuntu@192.168.1.50" -Mode Client `
        -SSHKeyPath "~/.ssh/id_ed25519" -MeshPSK $env:AITHER_MESH_PSK

.NOTES
    Author: Aitherium
    Version: 1.0.0
    Priority: P390 / P534
    Section: §71 DOM Deploy / §78 AitherProtocol
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory, Position = 0)]
    [string]$Target,

    [Parameter()]
    [ValidateSet("Client", "Node")]
    [string]$Mode = "Client",

    [Parameter()]
    [string]$MeshPSK = $env:AITHER_MESH_PSK,

    [Parameter()]
    [string]$Controller = "auto",

    [Parameter()]
    [string[]]$Services = @(),

    [Parameter()]
    [switch]$GPUEnabled,

    [Parameter()]
    [PSCredential]$Credential,

    [Parameter()]
    [string]$SSHKeyPath,

    [Parameter()]
    [ValidateSet("client", "worker", "edge")]
    [string]$Role = "client",

    [Parameter()]
    [string]$ContainerRegistry = "ghcr.io/aitherium",

    [Parameter()]
    [switch]$Force,

    [Parameter()]
    [switch]$DryRun
)

# ============================================================================
# CONFIGURATION
# ============================================================================

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

# AitherMesh configuration template
$MeshConfigTemplate = @"
# AitherMesh Configuration
# Generated by 0058_Provision-Aither.ps1

HOSTNAME={0}
ROLE={1}
CONTROLLER_URL={2}
MESH_PSK_HASH=
FIRST_BOOT=$(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")

# Advanced Configuration
HEARTBEAT_INTERVAL=30
DISCOVERY_PROTOCOL=auto
TAILSCALE_ENABLED=false
CONTAINER_REGISTRY={3}
LOG_LEVEL=info
DATA_DIR=/var/lib/aither
MODELS_DIR=/var/lib/aither/models
LOGS_DIR=/var/log/aither
GPU_ENABLED={4}
"@

# Linux install script
$LinuxInstallScript = @'
#!/bin/bash
set -euo pipefail

echo "════════════════════════════════════════════════════════════════════════"
echo "  AitherMesh Provisioning Script"
echo "════════════════════════════════════════════════════════════════════════"

MODE="$1"
GPU_ENABLED="$2"
REGISTRY="$3"

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    OS="unknown"
fi

echo "[1/5] Detected OS: $OS"

# Install Docker/Podman
echo "[2/5] Installing container runtime..."
if command -v podman &> /dev/null; then
    echo "  Podman already installed"
    RUNTIME="podman"
elif command -v docker &> /dev/null; then
    echo "  Docker already installed"
    RUNTIME="docker"
else
    case "$OS" in
        ubuntu|debian)
            apt-get update
            apt-get install -y podman
            RUNTIME="podman"
            ;;
        fedora|centos|rhel|rocky|almalinux)
            dnf install -y podman
            RUNTIME="podman"
            ;;
        *)
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com | sh
            RUNTIME="docker"
            ;;
    esac
fi
echo "  Using: $RUNTIME"

# Install NVIDIA drivers if GPU enabled
if [ "$GPU_ENABLED" = "true" ]; then
    echo "[3/5] Installing NVIDIA drivers..."
    if command -v nvidia-smi &> /dev/null; then
        echo "  NVIDIA drivers already installed"
        nvidia-smi --query-gpu=name --format=csv,noheader
    else
        case "$OS" in
            ubuntu|debian)
                apt-get install -y nvidia-driver-535 nvidia-container-toolkit
                ;;
            fedora|centos|rhel|rocky|almalinux)
                dnf install -y nvidia-driver nvidia-container-toolkit
                ;;
        esac
    fi
    
    # Configure container runtime for GPU
    if [ "$RUNTIME" = "podman" ]; then
        nvidia-ctk runtime configure --runtime=podman || true
    else
        nvidia-ctk runtime configure --runtime=docker || true
        systemctl restart docker || true
    fi
else
    echo "[3/5] Skipping GPU setup (not enabled)"
fi

# Create directories
echo "[4/5] Creating directories..."
mkdir -p /etc/aither
mkdir -p /var/lib/aither/{models,mesh}
mkdir -p /var/log/aither
mkdir -p /etc/aither/secrets

# Pull and run AitherMesh container
echo "[5/5] Deploying AitherMesh..."
if [ "$MODE" = "Client" ]; then
    IMAGE="${REGISTRY}/aitherclient:latest"
else
    IMAGE="${REGISTRY}/aithernode:latest"
fi

# Pull image
$RUNTIME pull "$IMAGE" || {
    echo "Warning: Could not pull $IMAGE, will try local deployment"
    # Fallback: Download Python agent
    if command -v python3 &> /dev/null; then
        pip3 install httpx fastapi uvicorn pyyaml
        # Download mesh agent
        curl -sL "https://raw.githubusercontent.com/Aitherium/AitherZero/main/AitherOS/AitherNode/services/mesh/AitherMesh.py" \
            -o /usr/local/bin/aither-mesh-agent.py || true
        chmod +x /usr/local/bin/aither-mesh-agent.py 2>/dev/null || true
    fi
}

echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  AitherMesh installation complete!"
echo "  Run: aither-mesh-agent join --controller auto"
echo "════════════════════════════════════════════════════════════════════════"
'@

# Windows install script
$WindowsInstallScript = @'
# AitherMesh Windows Provisioning
$ErrorActionPreference = "Stop"

Write-Host "════════════════════════════════════════════════════════════════════════"
Write-Host "  AitherMesh Provisioning Script (Windows)"
Write-Host "════════════════════════════════════════════════════════════════════════"

$Mode = $args[0]
$GPUEnabled = $args[1] -eq "true"
$Registry = $args[2]

# Check for Docker Desktop
Write-Host "[1/4] Checking Docker..."
$docker = Get-Command docker -ErrorAction SilentlyContinue
if (-not $docker) {
    Write-Host "  Docker not found. Installing Docker Desktop..."
    # Download and install Docker Desktop
    $dockerUrl = "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
    $installer = "$env:TEMP\DockerDesktopInstaller.exe"
    Invoke-WebRequest -Uri $dockerUrl -OutFile $installer
    Start-Process -FilePath $installer -ArgumentList "install", "--quiet" -Wait
    Write-Host "  Docker Desktop installed. Please restart and run again."
    exit 0
} else {
    Write-Host "  Docker found"
}

# Check for NVIDIA drivers if GPU enabled
if ($GPUEnabled) {
    Write-Host "[2/4] Checking NVIDIA drivers..."
    $nvidiaSmi = Get-Command nvidia-smi -ErrorAction SilentlyContinue
    if ($nvidiaSmi) {
        & nvidia-smi --query-gpu=name --format=csv,noheader
    } else {
        Write-Warning "  NVIDIA drivers not found. Please install manually."
    }
} else {
    Write-Host "[2/4] Skipping GPU setup"
}

# Create directories
Write-Host "[3/4] Creating directories..."
$dirs = @(
    "$env:ProgramData\Aither",
    "$env:ProgramData\Aither\models",
    "$env:ProgramData\Aither\mesh",
    "$env:ProgramData\Aither\logs",
    "$env:ProgramData\Aither\secrets"
)
foreach ($dir in $dirs) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

# Pull and run
Write-Host "[4/4] Deploying AitherMesh..."
$image = if ($Mode -eq "Client") { "${Registry}/aitherclient:latest" } else { "${Registry}/aithernode:latest" }

try {
    docker pull $image
} catch {
    Write-Warning "Could not pull $image. Install Python agent instead."
    # Fallback to Python
    if (Get-Command python -ErrorAction SilentlyContinue) {
        pip install httpx fastapi uvicorn pyyaml
    }
}

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════════════"
Write-Host "  AitherMesh installation complete!"
Write-Host "════════════════════════════════════════════════════════════════════════"
'@

# ============================================================================
# FUNCTIONS
# ============================================================================

function Get-TargetInfo {
    <#
    .SYNOPSIS
        Parse target string to extract user, host, and port
    #>
    param([string]$TargetString)
    
    $result = @{
        User = $null
        Host = $TargetString
        Port = 22
        IsWindows = $false
    }
    
    # Parse user@host format
    if ($TargetString -match "^(.+)@(.+)$") {
        $result.User = $Matches[1]
        $result.Host = $Matches[2]
    }
    
    # Parse host:port format
    if ($result.Host -match "^(.+):(\d+)$") {
        $result.Host = $Matches[1]
        $result.Port = [int]$Matches[2]
    }
    
    # Detect if Windows (by port or hostname)
    if ($result.Port -eq 5985 -or $result.Port -eq 5986) {
        $result.IsWindows = $true
    }
    
    return $result
}

function Invoke-SSHCommand {
    <#
    .SYNOPSIS
        Execute command on remote Linux host via SSH
    #>
    param(
        [string]$Host,
        [string]$Command,
        [string]$User = "root",
        [int]$Port = 22,
        [string]$KeyPath,
        [PSCredential]$Credential
    )
    
    $sshArgs = @("-o", "StrictHostKeyChecking=no", "-o", "BatchMode=yes")
    
    if ($KeyPath) {
        $sshArgs += @("-i", $KeyPath)
    }
    
    $sshArgs += @("-p", $Port)
    $sshArgs += "${User}@${Host}"
    $sshArgs += $Command
    
    if ($DryRun) {
        Write-Host "[DRY RUN] ssh $($sshArgs -join ' ')" -ForegroundColor Yellow
        return
    }
    
    $result = & ssh @sshArgs 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "SSH command failed: $result"
    }
    return $result
}

function Copy-FileToRemote {
    <#
    .SYNOPSIS
        Copy file to remote host via SCP
    #>
    param(
        [string]$LocalPath,
        [string]$RemotePath,
        [string]$Host,
        [string]$User = "root",
        [int]$Port = 22,
        [string]$KeyPath
    )
    
    $scpArgs = @("-o", "StrictHostKeyChecking=no", "-o", "BatchMode=yes")
    
    if ($KeyPath) {
        $scpArgs += @("-i", $KeyPath)
    }
    
    $scpArgs += @("-P", $Port)
    $scpArgs += $LocalPath
    $scpArgs += "${User}@${Host}:${RemotePath}"
    
    if ($DryRun) {
        Write-Host "[DRY RUN] scp $($scpArgs -join ' ')" -ForegroundColor Yellow
        return
    }
    
    & scp @scpArgs
    if ($LASTEXITCODE -ne 0) {
        throw "SCP failed"
    }
}

function Deploy-ToLinux {
    <#
    .SYNOPSIS
        Deploy AitherMesh to Linux target
    #>
    param(
        [hashtable]$TargetInfo,
        [string]$Mode,
        [switch]$GPUEnabled,
        [string]$Registry
    )
    
    $host_ = $TargetInfo.Host
    $user = $TargetInfo.User ?? "root"
    $port = $TargetInfo.Port
    
    Write-Host "`n🐧 Deploying to Linux: $user@$host_`:$port" -ForegroundColor Cyan
    
    # Create temp install script
    $scriptPath = Join-Path $env:TEMP "aither-install.sh"
    $LinuxInstallScript | Set-Content -Path $scriptPath -Force
    
    # Copy script to remote
    Write-Host "  Copying install script..."
    Copy-FileToRemote -LocalPath $scriptPath `
        -RemotePath "/tmp/aither-install.sh" `
        -Host $host_ -User $user -Port $port `
        -KeyPath $SSHKeyPath
    
    # Execute script
    Write-Host "  Running installation..."
    $gpuFlag = if ($GPUEnabled) { "true" } else { "false" }
    Invoke-SSHCommand -Host $host_ -User $user -Port $port -KeyPath $SSHKeyPath `
        -Command "chmod +x /tmp/aither-install.sh && sudo /tmp/aither-install.sh '$Mode' '$gpuFlag' '$Registry'"
    
    # Generate and copy mesh config
    Write-Host "  Configuring mesh..."
    $hostname = Invoke-SSHCommand -Host $host_ -User $user -Port $port -KeyPath $SSHKeyPath `
        -Command "hostname"
    
    $meshConfig = $MeshConfigTemplate -f @(
        $hostname.Trim(),
        $Role,
        $Controller,
        $Registry,
        $gpuFlag
    )
    
    $configPath = Join-Path $env:TEMP "mesh.conf"
    $meshConfig | Set-Content -Path $configPath -Force
    
    Copy-FileToRemote -LocalPath $configPath `
        -RemotePath "/etc/aither/mesh.conf" `
        -Host $host_ -User $user -Port $port `
        -KeyPath $SSHKeyPath
    
    # Store PSK securely
    if ($MeshPSK) {
        Write-Host "  Storing mesh PSK..."
        $pskHash = [System.BitConverter]::ToString(
            [System.Security.Cryptography.SHA256]::Create().ComputeHash(
                [System.Text.Encoding]::UTF8.GetBytes($MeshPSK)
            )
        ).Replace("-", "").ToLower()
        
        Invoke-SSHCommand -Host $host_ -User $user -Port $port -KeyPath $SSHKeyPath `
            -Command "echo '$MeshPSK' | sudo tee /etc/aither/secrets/mesh.psk > /dev/null && sudo chmod 600 /etc/aither/secrets/mesh.psk"
    }
    
    # Start mesh agent
    Write-Host "  Starting mesh agent..."
    try {
        Invoke-SSHCommand -Host $host_ -User $user -Port $port -KeyPath $SSHKeyPath `
            -Command "cd /var/lib/aither && python3 /usr/local/bin/aither-mesh-agent.py join --controller '$Controller' --role '$Role' 2>&1 || echo 'Agent start pending...'"
    } catch {
        Write-Warning "Mesh agent may need manual start. Run: aither-mesh-agent join"
    }
    
    Write-Host "`n✅ Linux deployment complete!" -ForegroundColor Green
}

function Deploy-ToWindows {
    <#
    .SYNOPSIS
        Deploy AitherMesh to Windows target via WinRM
    #>
    param(
        [hashtable]$TargetInfo,
        [string]$Mode,
        [switch]$GPUEnabled,
        [string]$Registry,
        [PSCredential]$Credential
    )
    
    $host_ = $TargetInfo.Host
    
    Write-Host "`n🪟 Deploying to Windows: $host_" -ForegroundColor Cyan
    
    # Create remote session
    $sessionParams = @{
        ComputerName = $host_
    }
    
    if ($Credential) {
        $sessionParams.Credential = $Credential
    }
    
    if ($TargetInfo.Port -eq 5986) {
        $sessionParams.UseSSL = $true
    }
    
    if ($DryRun) {
        Write-Host "[DRY RUN] Would connect to $host_ via WinRM" -ForegroundColor Yellow
        return
    }
    
    $session = New-PSSession @sessionParams
    
    try {
        # Run install script
        $gpuFlag = if ($GPUEnabled) { "true" } else { "false" }
        $result = Invoke-Command -Session $session -ScriptBlock {
            param($Script, $Mode, $GPU, $Reg)
            $scriptBlock = [scriptblock]::Create($Script)
            & $scriptBlock $Mode $GPU $Reg
        } -ArgumentList $WindowsInstallScript, $Mode, $gpuFlag, $Registry
        
        Write-Host $result
        
        # Configure mesh
        $hostname = Invoke-Command -Session $session -ScriptBlock { hostname }
        
        $meshConfig = $MeshConfigTemplate -f @(
            $hostname,
            $Role,
            $Controller,
            $Registry,
            $gpuFlag
        )
        
        Invoke-Command -Session $session -ScriptBlock {
            param($Config, $PSK)
            $Config | Set-Content -Path "$env:ProgramData\Aither\mesh.conf" -Force
            if ($PSK) {
                $PSK | Set-Content -Path "$env:ProgramData\Aither\secrets\mesh.psk" -Force
            }
        } -ArgumentList $meshConfig, $MeshPSK
        
        Write-Host "`n✅ Windows deployment complete!" -ForegroundColor Green
        
    } finally {
        Remove-PSSession $session
    }
}

# ============================================================================
# MAIN
# ============================================================================

# Banner
Write-Host @"

╔══════════════════════════════════════════════════════════════════════════╗
║                     AITHER PROVISIONING SCRIPT                            ║
║                     Deploy AitherMesh to Bare Metal                       ║
╚══════════════════════════════════════════════════════════════════════════╝

"@ -ForegroundColor Cyan

# Validate parameters
if (-not $MeshPSK -and -not $Force) {
    throw "MeshPSK is required. Set -MeshPSK or `$env:AITHER_MESH_PSK"
}

# Parse target
$targetInfo = Get-TargetInfo -TargetString $Target

Write-Host "📋 Configuration:" -ForegroundColor Cyan
Write-Host "   Target:     $($targetInfo.Host)" 
Write-Host "   Mode:       $Mode"
Write-Host "   Role:       $Role"
Write-Host "   GPU:        $($GPUEnabled.IsPresent)"
Write-Host "   Controller: $Controller"
Write-Host "   Services:   $($Services -join ', ')"
Write-Host ""

if ($PSCmdlet.ShouldProcess($Target, "Deploy Aither$Mode")) {
    
    if ($targetInfo.IsWindows -or $targetInfo.Port -eq 5985 -or $targetInfo.Port -eq 5986) {
        # Windows target
        Deploy-ToWindows -TargetInfo $targetInfo -Mode $Mode `
            -GPUEnabled:$GPUEnabled -Registry $ContainerRegistry `
            -Credential $Credential
    } else {
        # Linux target
        Deploy-ToLinux -TargetInfo $targetInfo -Mode $Mode `
            -GPUEnabled:$GPUEnabled -Registry $ContainerRegistry
    }
    
    # Summary
    Write-Host @"

╔══════════════════════════════════════════════════════════════════════════╗
║                       DEPLOYMENT COMPLETE                                  ║
╠══════════════════════════════════════════════════════════════════════════╣
║  Target:  $($targetInfo.Host.PadRight(60))║
║  Mode:    $($Mode.PadRight(60))║
║  Role:    $($Role.PadRight(60))║
╠══════════════════════════════════════════════════════════════════════════╣
║  Next Steps:                                                               ║
║    1. Verify in AitherVeil dashboard: http://localhost:3000               ║
║    2. Check mesh status: aither-mesh-agent status                          ║
║    3. View logs: journalctl -u aither-mesh -f (Linux)                     ║
╚══════════════════════════════════════════════════════════════════════════╝

"@ -ForegroundColor Green
}

